---
# tasks file for roles/app

  - name: Run api
    docker_container:
      name: backend
      image: tibserre/tp2:simple-api
      state: started
      pull: true
      recreate: true
      ports: 
        - "8080:8080"
