---
# tasks file for roles/proxy
  - name: Run HTTPD
    docker_container:
      name: httpd
      image: tibserre/tp2:httpd
      networks:
        - name: networkWala
      ports : 
        - "80:80"